# Generated by Django 5.0.7 on 2024-08-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("task_id", models.CharField(max_length=100)),
                ("status", models.CharField(default="processing", max_length=20)),
                ("model_data", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "glb_file",
                    models.FileField(blank=True, null=True, upload_to="models/"),
                ),
                (
                    "usdz_file",
                    models.FileField(blank=True, null=True, upload_to="models/"),
                ),
            ],
        ),
    ]
